fix error ERROR in src/app/app.component.ts(78,22): error TS2339: Property 'refresh' does not exist on type 'TableGridComponent'. move complex initialization from constructor method to ngOnInit extract logic in ngOnInit to loadGrid() method